### PR TITLE
Rewrite ToSqlPredicate to handle enums and skip using reflection

### PR DESCRIPTION
**Pull request by rykkart**
Rewrite `ToSqlPredicate` to handle Enums. Currently SQL with enums get converted to `(System.Int32)s.Type = (System.Int32)t.Type`.

The new suggested solution also skips the using of reflection.

### CODE REVIEW

**Comment by NorthernLight1** [comment]
rykkart,

Your branch failed to pass all the tests. I have put in my own fix for now, that I think is less risky. I would say that we stick with the existing logic in LinqExtensions.cs for now, I would like to have you add all the other code you did. If you don't' have time, I can  add in your code next week.

**Comment by rykkart** [comment]
Yes, seems like when adding the OrderStatus enum to the Order table a lot of tests failed. Seems to be a problem with the BulkFetch and BulkInsert with enums aswell. 

Which other code do you mean? The tests?

**Comment by NorthernLight1** [comment]
rykkart,

There are still some tests that are failing for this branch. If you do a merge into development instead of master, I can also help take a look at it.

**Comment by rykkart** [comment]
Yes I know. I will look into that.

**Comment by rykkart** [comment]
Question is how we would like the sql predicate to be generated. The one without reflection is worling but UPDATE still use the other logic.

**Comment by NorthernLight1** [comment]
rykkart, 

I think we should stick to using reflection for now. My concern is all the possible combinations you could use on the MergeOnConditon and UpdateOnCondition. Your code is good, but it would only work on a limited set of scenerios.

**Comment by rykkart** [comment]
I agree, than I suggest us to close this pull request.

**Pull request merged**
